# fly.toml app configuration file generated for hackathon-floral-sun-886 on 2025-04-08T20:34:17+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hackathon-floral-sun-886'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
