# fly.toml app configuration file generated for supabase-pusher-bridge on 2025-04-08T20:25:04+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hackathon-floral-sun-886'
primary_region = 'lax'

[build]

[env]
  PORT = '3001'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[checks]
  [checks.health]
    port = 3001
    type = 'http'
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'get'
    path = '/health'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
