/**
 * Pusher test endpoints
 */
const express = require('express');
const router = express.Router();
const logger = require('../utils/logger');
const pusherService = require('../services/pusher');

/**
 * POST /test-pusher
 * Test Pusher integration
 */
router.post('/', async (req, res) => {
  try {
    logger.info('Testing Pusher integration');
    const roomId = req.body.roomId || 'test-room';
    const message = req.body.message || 'Test message';
    const messageType = req.body.messageType || 'text';

    if (messageType === 'html') {
      // Test sending HTML content
      const htmlContent = req.body.htmlContent || `
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%); }
            .container { max-width: 800px; margin: 0 auto; background: white; padding: 20px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
            h1 { color: #4a6fa5; }
            p { line-height: 1.6; }
          </style>
        </head>
        <body>
          <div class="container">
            <h1>Test HTML Content</h1>
            <p>This is a test HTML page generated by the worker. In a real scenario, this would contain a creative summary or visualization of the conversation.</p>
            <p>The actual content would be much more detailed and relevant to the conversation topics.</p>
          </div>
        </body>
        </html>
      `;

      // Send HTML content as a special event type
      logger.info('Sending test HTML visualization to Pusher');

      const visualizationData = {
        id: 'test-viz-' + Date.now(),
        html: htmlContent,
        summary: 'Test HTML Visualization',
        created_at: new Date().toISOString(),
        user_id: 'test-user',
      };

      try {
        await pusherService.sendHtmlVisualization(roomId, visualizationData);
        logger.info('Test HTML visualization successfully sent to Pusher');
        res.status(200).json({
          success: true,
          message: 'Test HTML visualization sent to Pusher',
        });
      } catch (error) {
        logger.error('Error sending test HTML visualization to Pusher:', error);
        res.status(500).json({ error: 'Failed to send HTML visualization to Pusher' });
      }
    } else {
      // Regular text message
      await pusherService.sendNewMessage(roomId, {
        id: 'test-' + Date.now(),
        content: message,
        created_at: new Date().toISOString(),
        user_id: 'test-user',
      });

      res.status(200).json({ success: true, message: 'Test message sent to Pusher' });
    }
  } catch (error) {
    logger.error('Error testing Pusher:', error);
    res.status(500).json({ error: 'Failed to send test message to Pusher' });
  }
});

module.exports = router;