name: Build and Publish Docker Image, then deploy to hackerthem.xenon.fun

on:
  push:
    branches: [main] # Trigger on push to main branch
  pull_request:
    branches: [main] # Optional: Trigger on pull requests to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx (for multi-platform builds, optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Your Docker Hub username
          password: ${{ secrets.DOCKERHUB_TOKEN }}   # Your Docker Hub access token

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Build context (root of repo, where Dockerfile is located)
          file: ./Dockerfile # Path to Dockerfile (modify if not in root)
          push: true # Push to Docker Hub
          tags: |
            rsafier/hackerthem_worker:latest
            rsafier/hackerthem_worker:${{ github.sha }}
          platforms: linux/amd64 # Optional: Specify platform (add others if needed, e.g., linux/arm64)
      - name: Deploy to remote server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.HACKERTHEM_SSH_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key
          chmod 600 key
          ssh -i key -o StrictHostKeyChecking=no hackerthem@hackerthem.xenon.fun '/home/hackerthem/deploy-script.sh'
